name: Node.js CI

on:
  push:
    branches: [ ci-pipeline ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Instalar dependencias
      run: npm install

    - name: Dar permisos a Jest
      run: chmod +x ./node_modules/.bin/jest

    - name: Ejecutar pruebas
      run: npx jest

